export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_ID = 'GET_USER_ID';

export const GET_ALL_DOGS = 'GET_ALL_DOGS';
export const GET_MATCHES = 'GET_MATCHES';
export const INCREMENT_NEW_MATCHES = 'INCREMENT_NEW_MATCHES';
export const CLEAR_NEW_MATCHES = 'CLEAR_NEW_MATCHES';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_CURRENT_CHAT = 'GET_CURRENT_CHAT';
export const GET_CHAT_USER_LIST = 'GET_CHAT_USER_LIST';
export const SET_CHAT_USER = 'SET_CHAT_USER';
